### ISSUE TITLE
Submit drms for Review as an Affiliated Package

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#218]
## Package Details

- Package name: drms
- Maintainer(s): Kolja Glogowski
- Repository: https://github.com/sunpy/drms
- PyPI link (if applicable): https://pypi.org/project/drms

## Description of Package

The drms module provides an easy-to-use interface for accessing HMI, AIA and MDI data with Python. It uses the publicly accessible JSOC DRMS server by default, but can also be used with local NetDRMS sites. 

## Editor Submission Checklist

- [x] Is the submission appropriate?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Rapid Development / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@samaloney Would you be able to review this for me? :grin:

**Comment by samaloney** [comment]
* Relevant and Useful Functionality    : General Package
* Make use of all appropriate features : Well integrated
* Documentation                        : Extensive
* Testing                              : Good
* Duplication                          : Excellent
* Community Engagement                 : Excellent
* Maturity and Development Status      : Excellent

Testing is marked as good because as the tests are not run by a CI system and lowish coverage of 49% on master.

Per the guidelines Documentation is Excellent but could do with some developer documentation.

**Comment by Cadair** [comment]
Thanks for the review @samaloney.

I am adding the review to #215 :rocket:
