### ISSUE TITLE
Submit radiospectra for review as an Affiliated Package

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#219]
## Package Details

- Package name: radiospectra
- Maintainer(s): David Pérez-Suárez
- Repository: https://github.com/sunpy/radiospectra
- PyPI link (if applicable): https://pypi.org/project/radiospectra/

## Description of Package
This package aims to provide support for some types of radiospectra on solar physics.

## Editor Submission Checklist

- [x] Is the submission appropriate?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Rapid Development / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@dstansby would you be up for giving this a review please?

**Comment by nabobalis** [comment]
@dstansby do you have some time to do this?

**Comment by nabobalis** [comment]
Actually @dstansby, I will review it now, you can do more important things.

**Comment by nabobalis** [comment]
* **Functionality:** General Package ![img](https://img.shields.io/badge/General_Package-brightgreen.svg)

This package might be useful to anyone who wants to use spectra, which is a common type of data in solar physics.

* **Integration:** None ![img](https://img.shields.io/badge/Integration-Well_Integrated-brightgreen.svg)

Since this is old code removed from sunpy before 1.0, it has not seen any updates to use any changes from sunpy or ndcube since then.

* **Documentation:** Some ![img](https://img.shields.io/badge/Some-orange.svg)

The documentation is linked on the repository, resides on Read the Docs, and includes extensive API documentation but the guide is short and I question how up to date it is.

* **Testing:** Good ![img](https://img.shields.io/badge/Good-orange.svg

I could make a case for Needs Work but what tests are there are decent and cover much of of the user facing code. It also has CI but needs be updated to test more cases and packages.

* **Duplication:** Some ![img](https://img.shields.io/badge/Some-orange.svg)

sunraster now exists and so the scope of this package vs sunaster and how they interact is an important question to solve in the future.

* **Community:** Excellent ![img](https://img.shields.io/badge/Engagement-Excellent-brightgreen.svg)

It is part of the sunpy community?

* **Development Status:** Subject to Change ![img](https://img.shields.io/badge/Development_Status-Subject_to_change-orange.svg)

The package is on v0.2, pre-1.0, so breaking API changes are reasonable to expect. The question is how much development will it see in the future?
