### ISSUE TITLE
Submit pfsspy to be an affliated package

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#223]
## Package Details

- Package name: pfsspy
- Maintainer(s): David Stansby
- Repository: https://github.com/dstansby/pfsspy
- PyPI link (if applicable): https://pypi.org/project/pfsspy/

## Description of Package

A python Potential Field Source Surface model package.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Rapid Development / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@wtbarnes Could you review this one? :grin:

**Comment by wtbarnes** [comment]
* **Functionality:** Specialized Package ![img](https://img.shields.io/badge/Functionality-Specialized_Package-brightgreen.svg)
This package is useful to anyone who wants to do magnetic modeling using a potential field source surface model, a very common technique in solar physics. I say this is a specialized package not because it appeals to only a few in the community, but because the scope is relatively narrow.

* **Integration:** Well integrated ![img](https://img.shields.io/badge/Integration-Well_Integrated-brightgreen.svg)
The package uses both `SkyCoord` for describing field line traces as well as `sunpy.map.Maps` for representing two-dimensional magnetic field maps that provide the lower boundary condition. 

* **Documentation:** Extensive ![img](https://img.shields.io/badge/Documentation-Extensive-brightgreen.svg)
The documentation is linked on the repository, resides on Read the Docs, and includes both extensive API documentation as well as several examples

* **Testing:** Excellent ![img](https://img.shields.io/badge/Testing-Excellent-brightgreen.svg)
Coverage is reported from coveralls at 94%. The package is tested on Python 3.6-3.8 automatically on Travis CI. The package is also tested against development versions of sunpy and astropy to anticipate breaking changes.
 
* **Duplication:** None ![img](https://img.shields.io/badge/Duplication-None-brightgreen.svg)
pfsspy does not duplicate any functionality in the core package. While it does have overlap in scope with the solarbextrapolation package, that package is largely unmaintained so any duplication there is irrelevant.
 
* **Community:** Excellent ![img](https://img.shields.io/badge/Engagement-Excellent-brightgreen.svg)
Though pfsspy only has a single contributor, the author is closely engaged with the community, is a core SunPy contributor, and regularly seeks feedback on various components of the package from the community.
 
* **Development Status:** Subject to Change ![img](https://img.shields.io/badge/Development_Status-Subject_to_change-orange.svg)
The package is on v0.5.1, pre-1.0, so breaking API changes are reasonable to expect.

**Comment by Cadair** [comment]
> that package is largely unmaintained

for the record, solarbextrapolation has been shutdown and archived. It is dead Dave.

**Comment by wtbarnes** [comment]
> > that package is largely unmaintained
> 
> for the record, solarbextrapolation has been shutdown and archived. It is dead Dave.

Ha very true. I think I meant to write something more like archived. My sleepy brain disagreed

**Comment by wtbarnes** [comment]
It looks like pfsspy does not have a code of conduct which is a requirement for the community section. Did I just miss this @dstansby?

**Comment by Cadair** [comment]
There is this section in the readme: https://github.com/dstansby/pfsspy#code-of-conduct which references the sunpy one, which is enough. Might be good for @dstansby to add it to the docs as well, but it's enough I think?

**Comment by dstansby** [comment]
Yes, I added that yesterday so it may have been just before your review or not obvious. I will add it to the docs in time for the next stable release.

**Comment by wtbarnes** [comment]
Yep, I'm totally ok with that 👍
