### ISSUE TITLE
Affiliated Package Application for roentgen

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy.org#302]
## Package Details

- Package name: roentgen
- Maintainer(s): Steven Christe, Shane Maloney
- Repository: https://github.com/ehsteve/roentgen
- Documentation link: https://roentgen.readthedocs.io
- PyPI link (if applicable): https://pypi.org/project/roentgen/
- Continuous integration link(s): https://github.com/ehsteve/roentgen/actions
- Link to Code of Conduct or page describing adopted Code of Conduct:

## Description of Package

`roentgen` is a Python package for the quantitative analysis of the interaction of energetic x-rays with matter. This package is named after one of the discoverers of X-rays, [Wilhelm Röntgen](https://en.wikipedia.org/wiki/Wilhelm_Röntgen). Though it is not specific to solar physics it is used by solar physics missions such as [Solar Orbiter STIX](https://datacenter.stix.i4ds.net). The future solar x-ray mission, PADRE, will also use it. Given its wide utility, it would be beneficial for this package to be under the umbrella of an organization.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash)

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by nabobalis** [comment]
For @ehsteve, @samaloney and @DanRyanIrish attention.

**Comment by ehsteve** [comment]
Thank you @nabobalis!

**Comment by ehsteve** [comment]
This package is currently used by the Solar Orbiter STIX instrument and will be used by the smallsat mission called PADRE led by Berkeley. It contains functionality which is required for any X-ray mission.

**Comment by wtbarnes** [comment]
# Review of `roentgen` package

I reviewed the development version of this package on the main branch of the GitHub repository at [this commit](https://github.com/ehsteve/roentgen/tree/743e3923bccb6755a088ecc0ea23c3c88df40065).

* Functionality: ![img](https://img.shields.io/badge/Functionality-Specialized_Package-brightgreen.svg)
  This package is very useful to anyone wanting to analyze the interactions of x-rays with matter. While not explicitly related to solar physics or solar physics data analysis, the package is very useful to those designing x-ray detectors for solar observations.
 
* Integration: ![img](https://img.shields.io/badge/Integration-Full-brightgreen.svg)
  I'm marking this as fully integrated even though the package does not use sunpy. This is because there is no relevant functionality provided by sunpy that the package could make use of.
 
* Documentation : ![img](https://img.shields.io/badge/Documentation-Extensive-brightgreen.svg)
  The documentation is written in restructured text, rendered with sphinx, and hosted on Read the Docs. The documentation includes a high-level guide to the concepts underpinning the software, an example gallery, and API documentation. 

* Testing: ![img](https://img.shields.io/badge/Testing-Good-orange.svg)
  There are unit tests for each submodule and the tests are run automatically on GitHub actions using multiple Python versions and operating systems. The only reason I am marking this as "Good" and not "Excellent" is that I am not able to assess the test coverage of the package. I would recommend that codecov (or some similar coverage tool) be run on the repo as part of the CI.

* Duplication: ![img](https://img.shields.io/badge/Duplication-None-brightgreen.svg)
  This package provides functionality not provided in the core package or in any affiliated package. Thus, there is no duplication. I would recommend that the authors use the `plasmapy` package to replace the functionality for getting element symbols and atomic numbers in `roentgen/util/util.py`.

* Community: ![img](https://img.shields.io/badge/Community-Needs_Work-red.svg)
  I am only marking this as "needs work" because the project lacks a code of conduct. If the authors add a code of conduct (e.g. https://sunpy.org/coc) then this can be promoted to "excellent".

* Development Status: ![img](https://img.shields.io/badge/Development_Status-Stable-brightgreen.svg)
  The package is available on PyPI and is at version v1.0. The repository has seen development activity in the last six months.

**Comment by ehsteve** [comment]
@wtbarnes thank you so much for the review! Those are all good points. I'm willing to fix them now if that would help.

**Comment by Cadair** [comment]
You are encouraged to respond to the review :grinning:

**Comment by wtbarnes** [comment]
> @wtbarnes thank you so much for the review! Those are all good points. I'm willing to fix them now if that would help. Not sure if I am supposed to respond to the review.

yes please do!

**Comment by ehsteve** [comment]
Working on updates in this [PR](https://github.com/ehsteve/roentgen/pull/35). @samaloney would you be willing to review it and/or contribute to it?

**Comment by samaloney** [comment]
For sure

**Comment by Cadair** [comment]
@ehsteve let us know when you would like this re-reviewed.

**Comment by wtbarnes** [comment]
@ehsteve do you have timeline for wanting this re-reviewed? It looks like your PR to fix some the issues I raised is mostly done.

**Comment by ehsteve** [comment]
@wtbarnes I am doing a few more things to make things better. I could not help myself! Give me another month or so. Hope that is okay.

**Comment by ehsteve** [comment]
@wtbarnes sorry it took so long but I am FINALLY finished and have made a new release. Ready for another review please!

**Comment by ehsteve** [comment]
@wtbarnes just so you are aware that I fixed the bug you mentioned (and another bug) and made another release (v2.1.0).

**Comment by wtbarnes** [comment]
# Updated Review of `roentgen` package

I reviewed version 2.1 of this package.

* Functionality: ![img](https://img.shields.io/badge/Functionality-Specialized_Package-brightgreen.svg)
  This package is very useful to anyone wanting to analyze the interactions of x-rays with matter. While not explicitly related to solar physics or solar physics data analysis, the package is very useful to those designing x-ray detectors for solar observations.
 
* Integration: ![img](https://img.shields.io/badge/Integration-Full-brightgreen.svg)
  I'm marking this as fully integrated even though the package does not use sunpy. This is because there is no relevant functionality provided by sunpy that the package could make use of.
 
* Documentation : ![img](https://img.shields.io/badge/Documentation-Extensive-brightgreen.svg)
  The documentation is written in restructured text, rendered with sphinx, and hosted on Read the Docs. The documentation includes a high-level guide to the concepts underpinning the software, an example gallery, and API documentation. 

* Testing: ![img](https://img.shields.io/badge/Testing-Excellent-brightgreen.svg)
  There are unit tests for each submodule and the tests are run automatically on GitHub actions using multiple Python versions and operating systems. Code coverage is assessed using CodeCov and is currently at 80% coverage.

* Duplication: ![img](https://img.shields.io/badge/Duplication-None-brightgreen.svg)
  This package provides functionality not provided in the core package or in any affiliated package. Thus, there is no duplication. I would recommend that the authors use the `plasmapy` package to replace the functionality for getting element symbols and atomic numbers in `roentgen/util/util.py`.

* Community: ![img](https://img.shields.io/badge/Community-Excellent-brightgreen.svg)
  There are instructions for contributing and the README says that contributors must follow the SunPy code of conduct.

* Development Status: ![img](https://img.shields.io/badge/Development_Status-Stable-brightgreen.svg)
  The package is available on PyPI and is at version v2.1. The repository has seen development activity in the last six months.

**Comment by wtbarnes** [comment]
Given the scores above, *roentgen* is accepted as a SunPy affiliated package.

**Comment by nabobalis** [comment]
Closed by https://github.com/sunpy/sunpy.org/pull/352
