### ISSUE TITLE
Submit `demcmc` to be an affiliated package

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#361]
## Package Details

- Package name: demcmc
- Maintainer(s): @dstansby 
- Repository: https://github.com/dstansby/demcmc
- Documentation link: https://demcmc.readthedocs.io
- PyPI link (if applicable): https://pypi.org/project/demcmc/
- Continuous integration link(s): https://github.com/dstansby/demcmc/actions
- Link to Code of Conduct or page describing adopted Code of Conduct: https://github.com/dstansby/demcmc/blob/7b88b4f5fb169b22922dcaf7e6aa4aada1e2219b/CODE_OF_CONDUCT.md

## Description of Package
A package for estimating differential emission measures (DEMs) from observations of the Sun using Monte Carlo methods.

demcmc provides an interface for collecting information on emission lines together in one place (a list of [EmissionLine](https://demcmc.readthedocs.io/en/latest/api/index.html#demcmc.EmissionLine) objects), and running a DEM inversion on them (using [predict_dem_emcee()](https://demcmc.readthedocs.io/en/latest/api/index.html#demcmc.predict_dem_emcee)). Each [EmissionLine](https://demcmc.readthedocs.io/en/latest/api/index.html#demcmc.EmissionLine) object contains the intensity of an observed line, and the contribution function of that line. The inversion is carried out using Markov chain Monte carlo (MCMC) methods, with the [emcee package](https://emcee.readthedocs.io/en/stable/) used to run the sampling.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash)

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by wtbarnes** [comment]
@Cadair are you up for reviewing this?

**Comment by Cadair** [comment]
Yep, I can review this. I have no idea how or why I missed the notifications for this.

**Comment by ayshih** [comment]
Does the first `m` in `demcmc` stand for "measure" or "Markov"? =)  I keep wanting to inject an additional `m` into the name of this package.

**Comment by Cadair** [comment]
# Review

## Scores

* Functionality: ![Specialized Package](https://img.shields.io/badge/Specialized_Package-brightgreen.svg)
* Integration: ![Full Integration](https://img.shields.io/badge/Full_Integration-brightgreen.svg) <sup>1</sup>
* Documentation: ![Extensive](https://img.shields.io/badge/Extensive-brightgreen.svg)
* Testing: ![Good](https://img.shields.io/badge/Good-orange.svg)
* Duplication: ![None](https://img.shields.io/badge/None-brightgreen.svg)
* Community: ![Good](https://img.shields.io/badge/Good-orange.svg) <sup>2</sup>
* Development Status: ![Low Activity](https://img.shields.io/badge/Low_activity-orange.svg) <sup>3</sup>

## Comments

Overall this looks like a great package, which definitely has utility to those working with DEMs. Some points / justifications for the ratings above:

1. I have put full integration, but seemingly there is none at all with core or any other affiliated package? Is there scope for this in the future?
2. I only put good here because I felt there wasn't enough evidence to justify an excellent, but as the package is new this is understandable.
3. I have put low activity here because it seems to have been very quiet for the last few months. Do you feel this is fair, given the current level of developer effort? (i.e. do you think telling people this is a low activity package will reflect reality in the next year?).

## Outcome

Accepted.

**Comment by dstansby** [comment]
Thanks for taking the time to review!

> ## Comments
> 
> Overall this looks like a great package, which definitely has utility to those working with DEMs. Some points / justifications for the ratings above:
> 
>     1. I have put full integration, but seemingly there is none at all with core or any other affiliated package? Is there scope for this in the future?

There is scope in the future, specifically to

- take `GenericMap`s as input and automatically parallelise the calculation over pixels.
- integrate closely with an emission measure calculation software (e.g. fiasco) if/when there is one of those that gains affiliated status

Unfortunately I didn't have time/funding to look at these yet. 

>     2. I only put good here because I felt there wasn't enough evidence to justify an excellent, but as the package is new this is understandable.

👍 this is fair, especially since it was a time limited project and I don't have further time/funding to build a community.

>     3. I have put low activity here because it seems to have been very quiet for the last few months. Do you feel this is fair, given the current level of developer effort? (i.e. do you think telling people this is a low activity package will reflect reality in the next year?).

👍 also very fair, without anyone else proactively contributing I won't be working on this more in the near future.

**Comment by Cadair** [comment]
You want to open the PR to add this to the list or shall I?

**Comment by dstansby** [comment]
I'm having a sunpy day, so I can do it later 👍
