### ISSUE TITLE
Submit `dkist` as an affiliated package

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#373]
## Package Details

- Package name: `dkist`
- Maintainer(s): NSO/DKIST Data Center, Stuart Mumford
- Repository: https://github.com/DKISTDC/dkist
- Documentation link: https://docs.dkist.nso.edu/projects/python-tools/
- PyPI link (if applicable): https://pypi.org/project/dkist/
- Continuous integration link(s): https://github.com/DKISTDC/dkist/actions  https://readthedocs.com/projects/dkistdc-dkist/
- Link to Code of Conduct or page describing adopted Code of Conduct: https://github.com/DKISTDC/dkist/blob/main/CODE_OF_CONDUCT.md

## Description of Package
The DKIST Python tools provide a package ([dkist](https://docs.dkist.nso.edu/projects/python-tools/en/latest/reference.html#module-dkist)) which aims to help you search, obtain and use DKIST data as part of your Python software.
The `dkist` package provides DKIST specific functionality on top of `sunpy`, `ndcube`, `astropy`, `gwcs` and `dask` to search for, download, work with and visualise DKIST data.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash)

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by wtbarnes** [comment]
# Review of `dkist` package

I reviewed the v1.0.0b15 of the `dkist` package.

* Functionality: ![img](https://img.shields.io/badge/Functionality-Specialized_Package-brightgreen.svg)
  This package is very useful to anyone wanting to search for, download, and load data from the new Daniel K. Inouye Solar Telescope. DKIST is the largest solar telescope in the world, thus this package is very relevant to solar physics.
 
* Integration: ![img](https://img.shields.io/badge/Integration-Full-brightgreen.svg)
  The package makes use of the `sunpy` package primarily for data search via `Fido`. The package also makes use of NDCube as its base data structure.
 
* Documentation : ![img](https://img.shields.io/badge/Documentation-Good-orange.svg)
  The documentation is written in restructured text, rendered with sphinx, and hosted on Read the Docs. The documentation includes a high-level guide to the concepts underpinning the software, and API documentation. I am only marking the documentation as "good" (as opposed to "extensive") because I did not see a tutorial (similar to the SunPy Tutorial) that showed a user how to get going quickly. The User Guide contains elements of this, but mixes reference material with conceptual material. It would be beneficial to provide better separation between these types of documentation (e.g. the diátaxis approach). I would also recommend providing more info in the README on GitHub.

* Testing: ![img](https://img.shields.io/badge/Testing-Good-orange.svg)
  I am only marking this as "good" as opposed to "excellent" because I could not easily find what the test coverage actually is (though looking at the codebase I assume it is high). Adding a codecov badge to the README would bump this to "excellent".

* Duplication: ![img](https://img.shields.io/badge/Duplication-None-brightgreen.svg)
  This package does not duplicate any functionality already provided by the SunPy Ecosystem.

* Community: ![img](https://img.shields.io/badge/Community-Excellent-brightgreen.svg)
  There is a CoC and there are multiple contributors to this repository. The documentation provides explicit instructions for getting help and contributing.

* Development Status: ![img](https://img.shields.io/badge/Development_Status-Stable-brightgreen.svg)
  The package is available on PyPI. The repository has seen development activity in the last six months.

**Comment by Cadair** [comment]
Thanks for the review @wtbarnes I have added a codecov badge (and a bunch of other badges) to the readme. I complete agree on the documentation, there's still lots to do there.
